modLoader = "javafml"
loaderVersion = "[${forge_major},)"
license = "MIT"

[[mods]]
modId = "mct"
version = "${version}"
displayName = "Minecraft Auto Test Client Mod"
description = "Real client bridge for Minecraft Auto Test."

[[dependencies.mct]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.mct]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version}]"
ordering = "NONE"
side = "CLIENT"
