modLoader = "javafml"
loaderVersion = "[2,)"
license = "All Rights Reserved"

[[mods]]
modId = "mct"
version = "${file.jarVersion}"
displayName = "Minecraft Auto Test Client Mod"
description = "Real client bridge for Minecraft Auto Test."

[[dependencies.mct]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.mct]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,1.22)"
ordering = "NONE"
side = "CLIENT"
