apply plugin: "net.minecraftforge.gradle.forge"

sourceCompatibility = targetCompatibility = "1.8"

minecraft {
    version = "1.12.2-14.23.5.2847"
    mappings = "stable_39"
    runDir = "run"
}

sourceSets {
    main {
        java.srcDir "../../shared/forge-1.12/java"
        resources.srcDir "../../shared/forge-1.12/resources"
    }
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", "1.12.2"
    from(sourceSets.main.resources.srcDirs) {
        include "mcmod.info"
        expand version: project.version, mc_version: "1.12.2"
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude "mcmod.info"
    }
}

jar {
    baseName = "mct-client-mod-forge-1.12.2"
    version = ""
}
