modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "mct"
version = "${file.jarVersion}"
displayName = "Minecraft Auto Test Client Mod"
description = "Real client bridge for Minecraft Auto Test."

[[dependencies.mct]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.mct]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.22)"
ordering = "NONE"
side = "CLIENT"
