export const IPC_CHANNELS = {
  GET_SERVER_STATE: "get-server-state",
  GET_CLIENT_STATE: "get-client-state",
  GET_PROJECTS: "get-projects",
  GET_CLIENT_INSTANCES: "get-client-instances",
  EXEC_MCT: "exec-mct",
  STATE_CHANGED: "state-changed",
  TAIL_LOG: "tail-log",
  TAIL_LOG_LINE: "tail-log-line",
  SELECT_FILE: "select-file",
  PTY_SPAWN: "pty-spawn",
  PTY_WRITE: "pty-write",
  PTY_RESIZE: "pty-resize",
  PTY_KILL: "pty-kill",
  PTY_DATA: "pty-data",
  PTY_EXIT: "pty-exit",
  PTY_HAS_SESSION: "pty-has-session",
  PTY_GET_SCROLLBACK: "pty-get-scrollback",
  OPEN_PATH: "open-path"
} as const;
